/**
 * Seed / demo polls shown when the database has no real data.
 * These give the site a professional, populated look for new visitors.
 * They are automatically hidden once real polls exist.
 */
import { type DemoPoll, PollStatus } from "@/lib/types";

const now = Math.floor(Date.now() / 1000);
const DAY = 86_400;
const HOUR = 3_600;
const LAMPORT = 1_000_000_000; // 1 SOL in lamports

function seed(partial: Partial<DemoPoll> & Pick<DemoPoll, "title" | "options" | "category">): DemoPoll {
  const optionCount = partial.options.length;
  return {
    id: `seed-${partial.title.replace(/\s+/g, "-").toLowerCase().slice(0, 30)}`,
    pollId: Math.floor(Math.random() * 100000),
    creator: "demo",
    description: partial.description ?? "",
    imageUrl: "",
    optionImages: [],
    voteCounts: partial.voteCounts ?? new Array(optionCount).fill(0).map(() => Math.floor(Math.random() * 80) + 5),
    unitPriceCents: partial.unitPriceCents ?? 0.01 * LAMPORT,
    endTime: partial.endTime ?? now + 7 * DAY,
    totalPoolCents: partial.totalPoolCents ?? Math.floor(Math.random() * 5 * LAMPORT + 0.5 * LAMPORT),
    creatorInvestmentCents: 0,
    platformFeeCents: 0,
    creatorRewardCents: 0,
    status: partial.status ?? PollStatus.Active,
    winningOption: partial.winningOption ?? 255,
    totalVoters: partial.totalVoters ?? Math.floor(Math.random() * 60) + 10,
    createdAt: partial.createdAt ?? now - Math.floor(Math.random() * 3 * DAY),
    ...partial,
  };
}

export const SEED_POLLS: DemoPoll[] = [
  seed({
    title: "Will Bitcoin hit $150K by end of 2026?",
    description: "Predict whether BTC will reach the $150,000 milestone before January 1, 2027.",
    options: ["Yes", "No"],
    category: "Crypto",
    voteCounts: [124, 89],
    totalVoters: 213,
    totalPoolCents: Math.floor(12.5 * LAMPORT),
    endTime: now + 30 * DAY,
    createdAt: now - 2 * DAY,
  }),
  seed({
    title: "Who will win the 2026 FIFA World Cup?",
    description: "The 2026 FIFA World Cup is hosted across USA, Canada & Mexico. Which team takes the trophy?",
    options: ["Brazil", "France", "Argentina", "Germany", "England", "Other"],
    category: "Sports",
    voteCounts: [78, 95, 112, 42, 56, 31],
    totalVoters: 414,
    totalPoolCents: Math.floor(24.3 * LAMPORT),
    endTime: now + 90 * DAY,
    createdAt: now - 5 * DAY,
  }),
  seed({
    title: "Will the Fed cut rates before July 2026?",
    description: "Prediction on whether the US Federal Reserve will announce at least one rate cut before July 1, 2026.",
    options: ["Yes — at least one cut", "No — rates stay or rise"],
    category: "Economics",
    voteCounts: [67, 53],
    totalVoters: 120,
    totalPoolCents: Math.floor(8.7 * LAMPORT),
    endTime: now + 14 * DAY,
    createdAt: now - 1 * DAY,
  }),
  seed({
    title: "Will Solana flip Ethereum in daily transactions by Q3 2026?",
    description: "Will Solana's average daily transaction count exceed Ethereum's before October 1, 2026?",
    options: ["Yes", "No"],
    category: "Crypto",
    voteCounts: [91, 64],
    totalVoters: 155,
    totalPoolCents: Math.floor(9.1 * LAMPORT),
    endTime: now + 60 * DAY,
    createdAt: now - 3 * DAY,
  }),
  seed({
    title: "Next US President's party in 2028?",
    description: "Which party will win the 2028 presidential election?",
    options: ["Democrat", "Republican", "Independent / Other"],
    category: "Politics",
    voteCounts: [88, 102, 14],
    totalVoters: 204,
    totalPoolCents: Math.floor(15.2 * LAMPORT),
    endTime: now + 180 * DAY,
    createdAt: now - 4 * DAY,
  }),
  seed({
    title: "Will GPT-5 be released before mid-2026?",
    description: "Prediction on whether OpenAI will publicly release GPT-5 (or equivalent next-gen model) before July 1, 2026.",
    options: ["Yes", "No"],
    category: "Tech",
    voteCounts: [143, 67],
    totalVoters: 210,
    totalPoolCents: Math.floor(11.8 * LAMPORT),
    endTime: now + 10 * DAY,
    createdAt: now - 6 * HOUR,
  }),
  seed({
    title: "Oscar Best Picture 2027 — Genre prediction",
    description: "What genre will the 2027 Best Picture winner belong to?",
    options: ["Drama", "Sci-Fi", "Comedy", "Thriller", "Animation"],
    category: "Entertainment",
    voteCounts: [65, 34, 21, 47, 12],
    totalVoters: 179,
    totalPoolCents: Math.floor(6.4 * LAMPORT),
    endTime: now + 120 * DAY,
    createdAt: now - 2 * DAY,
  }),
  seed({
    title: "Will global average temp exceed +1.5°C in 2026?",
    description: "Will 2026's global average temperature anomaly officially exceed the 1.5°C Paris Agreement threshold?",
    options: ["Yes", "No"],
    category: "Climate",
    voteCounts: [76, 58],
    totalVoters: 134,
    totalPoolCents: Math.floor(4.9 * LAMPORT),
    endTime: now + 45 * DAY,
    createdAt: now - 8 * HOUR,
  }),
  seed({
    title: "Will CRISPR cure a genetic disease by 2027?",
    description: "Will a CRISPR-based therapy receive full regulatory approval for curing a genetic condition before 2027?",
    options: ["Yes", "No", "Already happened"],
    category: "Science",
    voteCounts: [54, 39, 22],
    totalVoters: 115,
    totalPoolCents: Math.floor(3.8 * LAMPORT),
    endTime: now + 60 * DAY,
    createdAt: now - 1 * DAY,
  }),
  seed({
    title: "Will TikTok be banned in the US by 2027?",
    description: "Will TikTok face a complete operational ban in the United States before January 1, 2027?",
    options: ["Yes — full ban", "No — stays available", "Partial restriction"],
    category: "Culture",
    voteCounts: [48, 87, 33],
    totalVoters: 168,
    totalPoolCents: Math.floor(7.2 * LAMPORT),
    endTime: now + 30 * DAY,
    createdAt: now - 12 * HOUR,
  }),
  seed({
    title: "Apple stock above $250 by end of 2026?",
    description: "Will AAPL close above $250 on December 31, 2026?",
    options: ["Yes", "No"],
    category: "Companies",
    voteCounts: [62, 45],
    totalVoters: 107,
    totalPoolCents: Math.floor(5.5 * LAMPORT),
    endTime: now + 90 * DAY,
    createdAt: now - 3 * DAY,
  }),
  seed({
    title: "Will Elon Musk make a major announcement this month?",
    description: "Will Elon Musk make a headline-grabbing announcement (product launch, acquisition, etc.) within the current month?",
    options: ["Yes", "No"],
    category: "Mentions",
    voteCounts: [93, 41],
    totalVoters: 134,
    totalPoolCents: Math.floor(4.1 * LAMPORT),
    endTime: now + 5 * DAY,
    createdAt: now - 4 * HOUR,
  }),
];
